platform :ios, '7.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'Masonry','~>0.6'
pod 'CocoaAsyncSocket','~>7.4.2'
pod 'MJRefresh','~>3.1.0'
pod 'FMDB', '~> 2.6'
pod 'FDFullscreenPopGesture', '1.1'
pod 'SSCheckBoxView', '~> 0.0.1'
